# Generated by Django 4.2.7 on 2023-11-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('tipo_conta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_conta', models.IntegerField()),
                ('agencia', models.CharField(max_length=3)),
                ('senha', models.CharField(max_length=8)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimentacao', models.CharField(choices=[('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('DEPOSITO', 'Depósito')], default=True, max_length=20)),
                ('id_cliente_conta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clienteconta')),
            ],
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cartao', models.IntegerField()),
                ('ativo', models.BooleanField()),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente_conta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clienteconta')),
            ],
        ),
    ]
