# Generated by Django 4.2.7 on 2023-11-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('tipo_conta', models.CharField(choices=[('PF', 'PESSOA FISICA'), ('PJ', 'PESSOA JURIDICA')], max_length=20)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(default='', max_length=8)),
                ('cidade', models.CharField(default='', max_length=80)),
                ('uf', models.CharField(default='', max_length=2)),
                ('endereco', models.CharField(default='', max_length=255)),
                ('bairro', models.CharField(default='', max_length=80)),
                ('num_casa', models.CharField(default=None, max_length=6)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_conta', models.IntegerField()),
                ('agencia', models.CharField(default='0001', max_length=4)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_cliente', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimentacao', models.CharField(choices=[('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('DEPOSITO', 'Depósito')], default=True, max_length=20)),
                ('id_cliente_conta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clienteconta')),
            ],
        ),
        migrations.CreateModel(
            name='CartaoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cartao_debito', models.CharField(max_length=16)),
                ('ativo', models.BooleanField()),
                ('senha_debito', models.IntegerField()),
                ('cvv_debito', models.IntegerField()),
                ('id_cliente_conta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clienteconta')),
            ],
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cartao_credito', models.CharField(default=True, max_length=16)),
                ('ativo', models.BooleanField()),
                ('senha_credito', models.CharField(default=True, max_length=6)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cvv_credito', models.IntegerField(default=True)),
                ('id_cliente_conta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clienteconta')),
            ],
        ),
    ]
