# Generated by Django 4.2.7 on 2023-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaodebito',
            name='senha_debito',
            field=models.IntegerField(),
        ),
    ]
