# Generated by Django 4.2.7 on 2023-11-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimentacao',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tipo_movimentacao',
            new_name='transaction_type',
        ),
    ]
