# Generated by Django 4.2.7 on 2023-11-17 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteconta',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
