# Generated by Django 4.2.7 on 2023-11-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaocredito',
            name='num_cartao',
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='cvv_credito',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='num_cartao_credito',
            field=models.CharField(default=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='senha_credito',
            field=models.CharField(default=True, max_length=6),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_casa',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='clienteconta',
            name='id_cliente',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_conta',
            field=models.CharField(choices=[('PF', 'PESSOA FISICA'), ('PJ', 'PESSOA JURIDICA')], max_length=20),
        ),
        migrations.CreateModel(
            name='CartaoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cartao_debito', models.CharField(max_length=16)),
                ('ativo', models.BooleanField()),
                ('senha_debito', models.CharField(max_length=4)),
                ('cvv_debito', models.IntegerField()),
                ('id_cliente_conta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clienteconta')),
            ],
        ),
    ]
