# Generated by Django 4.2.7 on 2023-12-05 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustomer',
            name='id_cliente',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ac_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extract',
            name='id_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacao', to='Cliente.transaction'),
        ),
    ]
