# Generated by Django 4.2.7 on 2023-12-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_rename_id_cliente_conta_transaction_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id_cliente_conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cliente.accountcustomer'),
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('DEPOSITO', 'Depósito')], default=True, max_length=20)),
                ('conta_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Cliente.accountcustomer')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Cliente.accountcustomer')),
            ],
        ),
    ]
