# Generated by Django 4.2.7 on 2023-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_alter_accountcustomer_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='id_cliente_conta',
            new_name='id_cliente',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
