# Generated by Django 4.2.7 on 2023-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_rename_id_cliente_conta_loan_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
