# Generated by Django 4.2.7 on 2023-11-26 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_loan_delete_investimento_transaction_conta_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='conta_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='Cliente.accountcustomer'),
        ),
    ]
