# Generated by Django 4.2.7 on 2023-11-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_transaction_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_cliente_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to='Cliente.accountcustomer'),
        ),
    ]
