# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('DEPOSITO', 'Depósito'), ('DEBITO', 'Débito')], default=True, max_length=20),
        ),
    ]
