# Generated by Django 4.2.7 on 2023-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_alter_customer_options_remove_customer_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
