# Generated by Django 4.2.7 on 2023-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_alter_clienteconta_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteconta',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
