# Generated by Django 4.2.7 on 2023-11-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_alter_transaction_id_cliente_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustomer',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id_cliente_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.accountcustomer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('DEPOSITO', 'Depósito')], default=True, max_length=20),
        ),
    ]
