# Generated by Django 4.2.7 on 2023-11-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_alter_accountcustomer_saldo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcustomer',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
