# Generated by Django 4.2.7 on 2023-11-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_alter_accountcustomer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustomer',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id_cliente_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.accountcustomer'),
        ),
    ]
