# Generated by Django 4.2.7 on 2023-11-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_alter_accountcustomer_saldo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id_cliente_conta',
            new_name='id_cliente',
        ),
    ]
