# Generated by Django 4.2.7 on 2023-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_alter_accountcustomer_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
