# Generated by Django 4.2.7 on 2023-11-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0009_alter_transaction_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id_cliente_conta',
            new_name='id_cliente',
        ),
    ]
